# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpwarp" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "18c788bc7a00d9d1e2e83cbe919a2a858f54a0b7b427d95e200af48a88600abf"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "04d7fb34208f305ffed5e7c56eecb0b995dcbdb5aaa77002c9f01bb00b6c8ebd"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a41b91cc9b5cb1ad76d48aab2f5dfc71237023d6495da8bddb7c4ce9b492c854"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b4248e47280e0dc75e09ac39842ba6c7b09843323cd04db4045f17b7ca1296e"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpwarp"
  desc "CLI for tunneling and bridging MCP servers."
  homepage "https://github.com/mcpwarp/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpwarp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpwarp"]
    end
  end

  # No zap stanza required
end
