# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpwarp" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "1c294d1d137441561bb3413dc36dc70edcbf147a0f1187505a63beec4100b2e6"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bebe9e78d4bdaba7e02d96e9d62b4ed555a7dcf8e5485453a8a8f2a30dd08112"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "33b4ca472ebd24e6965789cf381e55f6655f9f25391d4e0b8facc84610011acb"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d88c18999de4bf5424a160665880045a50d4acffae8b840dcf47050ed5f8db4"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpwarp"
  desc "CLI for tunneling and bridging MCP servers."
  homepage "https://github.com/mcpwarp/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpwarp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpwarp"]
    end
  end

  # No zap stanza required
end
