# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpwarp" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "1c88fdbed781effaf38cc6b9b4a1ddb91697742ff817861f6dd0645c824a6aab"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "83974d19143cc10924c0f734f757fe84d6622bebdbf0fcd9b204f2c549e39906"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d0574e3dc15b972c4611aac1c174a81d600ebdaf8e04a3dd6140c05b6690f289"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "df6720367c2f711c6e60668d435e3d0c5205d05926c68330a972cc17a291434a"
      url "https://github.com/mcpwarp/cli/releases/download/v#{version}/mcpwarp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpwarp"
  desc "CLI for tunneling and bridging MCP servers."
  homepage "https://github.com/mcpwarp/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpwarp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpwarp"]
    end
  end

  # No zap stanza required
end
